name: Lint and Format

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint-and-format:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier check
        id: prettier
        run: npm run format:check
        continue-on-error: true

      - name: Annotate ESLint issues
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "::error::ESLint found issues in your code. Run 'npm run lint:fix' to automatically fix them."
          exit 1

      - name: Annotate Prettier issues
        if: steps.prettier.outcome == 'failure'
        run: |
          echo "::error::Prettier formatting check failed. Run 'npm run format' to format your code."
          exit 1

      - name: Summary
        if: failure()
        run: |
          echo "## ❌ Code Quality Check Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.eslint.outcome }}" == "failure" ]; then
            echo "- **ESLint**: Failed ❌" >> $GITHUB_STEP_SUMMARY
            echo "  - Fix with: \`npm run lint:fix\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **ESLint**: Passed ✅" >> $GITHUB_STEP_SUMMARY
          fi
          if [ "${{ steps.prettier.outcome }}" == "failure" ]; then
            echo "- **Prettier**: Failed ❌" >> $GITHUB_STEP_SUMMARY
            echo "  - Fix with: \`npm run format\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Prettier**: Passed ✅" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Success summary
        if: success()
        run: |
          echo "## ✅ Code Quality Check Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **ESLint**: Passed ✅" >> $GITHUB_STEP_SUMMARY
          echo "- **Prettier**: Passed ✅" >> $GITHUB_STEP_SUMMARY
